### ISSUE TITLE
The numpower-image link doesn't exist anymore

### ISSUE THREAD

**Issue by CViniciusSDias** [NumPower/numpower-docs#1]
At https://numpower.org/docs/image-processing we see a link to https://github.com/NumPower/numpower-image, but that repository doesn't exist

**Comment by henrique-borba** [comment]
I removed the repository before updating the documentation, thanks for noticing. The latest update (#2) removes information about numpower-image from the documentation.

I decided to temporarily remove the imaging project to focus my efforts on ML and artificial intelligence as the imaging lab did not look promising at the current stage of NumPower.

The way it was being done, GD would be a better option in any case and for it to be a match, it would be necessary to implement some specific features that are currently not necessary for the main focus.

Thanks @CViniciusSDias and great youtube videos btw, keep it up!
